language: python

python:
  - 2.7
  - 3.5.5

sudo: required

install:
  - sudo apt-get install gfortran python-liblas libblas-dev liblapack-dev libatlas-dev
  - pip install --upgrade pip
  - make install

script:
  - pip install tensorflow
  - pytest tests/test_detect.py
  - pytest tests/test_preprocess.py
  - pytest tests/test_cluster.py
  - pytest tests/test_templates.py
  - pytest tests/test_deconvolution.py

after_success: coveralls
